[package]
name = "ic-canister"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.3"
ic-canister-macros = { path = "../ic-canister-macros" }
ic-storage = { path = "../../ic-storage" }

[dev-dependencies]
serde = "1.0"
tokio-test = "0.4"
