[package]
name = "ic-stable-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stable-structures = { git = "https://github.com/dfinity/ic" }
